### ISSUE TITLE
open/ted/github show errors

### ISSUE THREAD

**Issue by mosluce** [WeiChiaChang/howhow-cli#4]
- os: macOS 10.13 (High Sierra)
- node version: v8.6.0
- howhow version: 1.0.86

error logs:

1. howhow open

```shell
Error: Exited with code 1
    at ChildProcess.cp.once.code (/Users/mosluce/.nvm/versions/node/v8.6.0/lib/node_modules/howhow/node_modules/opn/index.js:82:13)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
```

2. howhow ted

```shell
Error: Exited with code 1
    at ChildProcess.cp.once.code (/Users/mosluce/.nvm/versions/node/v8.6.0/lib/node_modules/howhow/node_modules/opn/index.js:82:13)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
```

3. howhow github
```shell
Error: Exited with code 1
    at ChildProcess.cp.once.code (/Users/mosluce/.nvm/versions/node/v8.6.0/lib/node_modules/howhow/node_modules/opn/index.js:82:13)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
```

**Comment by WeiChiaChang** [comment]
哇會噴錯啊 ＱＱ
我的環境是
mac OS ： 10.11.6
node     ：  8.5.0
@mosluce 我試著解決看看，感謝你的回報～！

**Comment by billcccheng** [comment]
maybe a `npm install` will fix this?

**Comment by WeiChiaChang** [comment]
Hello @mosluce,

So the other function like `$ howhow` works as expected right ?
Maybe you can try to upgrade your `npm` version although I'm not sure if this issue can be solved QQ since `opn` this npm module occur some bugs or not.

Btw, you can try the above advice given by @billcccheng , thanks !
